name: Fucking
run-name: ${{ github.actor }} is testing out GitHub Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: make-install
      - run: make-start
  tests:
    steps:
      - run: make-test
  lint:
    steps:
      - run: make-lint
